/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Asset = string;
export interface Dataset {
  'id' : DatasetId,
  'file' : ExternalBlob,
  'name' : string,
  'rows' : Array<SignalRow>,
  'uploadedAt' : Timestamp,
}
export type DatasetId = bigint;
export type ExternalBlob = Uint8Array;
export interface Settings {
  'rsiEmbedLow' : number,
  'bbStdDev' : number,
  'rsiPeriod' : bigint,
  'rsiEmbedHigh' : number,
  'rsiOversold' : number,
  'rsiOverbought' : number,
  'bbLength' : bigint,
  'minMinutesIntoBar' : number,
  'minBandWidthRatio' : number,
}
export interface SignalRow {
  'low' : number,
  'rsi' : number,
  'longSnapback' : boolean,
  'shortSnapback' : boolean,
  'ticker' : string,
  'asset' : Asset,
  'bbLower' : number,
  'timeframe' : Timeframe,
  'decisionEvent' : string,
  'high' : number,
  'mode' : string,
  'close' : number,
  'name' : string,
  'open' : number,
  'time' : string,
  'bbUpper' : number,
  'bbBasis' : number,
  'alertId' : string,
  'pushThrough' : boolean,
  'inSession' : boolean,
  'minutesIntoBar' : number,
  'bandWidth' : number,
  'touchDepthRatio' : number,
  'touchDepth' : number,
  'signalType' : SignalType,
}
export type SignalType = { 'snapbackLong' : null } |
  { 'pushThroughShort' : null } |
  { 'pushThroughLong' : null } |
  { 'snapbackShort' : null } |
  { 'noTrade' : null };
export type Timeframe = string;
export type Timestamp = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__datasets' : ActorMethod<
    [[] | [DatasetId], [] | [bigint]],
    Array<[DatasetId, Dataset]>
  >,
  '__nextId' : ActorMethod<[], any>,
  '__settings' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getDataset' : ActorMethod<[DatasetId], [] | [Dataset]>,
  'getDatasetRows' : ActorMethod<[DatasetId], [] | [Array<SignalRow>]>,
  'getSettings' : ActorMethod<[], Settings>,
  'listDatasets' : ActorMethod<[], Array<Dataset>>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
  'uploadDataset' : ActorMethod<[string, ExternalBlob], DatasetId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];