/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DatasetId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Asset = IDL.Text;
export const Timeframe = IDL.Text;
export const SignalType = IDL.Variant({
  'snapbackLong' : IDL.Null,
  'pushThroughShort' : IDL.Null,
  'pushThroughLong' : IDL.Null,
  'snapbackShort' : IDL.Null,
  'noTrade' : IDL.Null,
});
export const SignalRow = IDL.Record({
  'low' : IDL.Float64,
  'rsi' : IDL.Float64,
  'longSnapback' : IDL.Bool,
  'shortSnapback' : IDL.Bool,
  'ticker' : IDL.Text,
  'asset' : Asset,
  'bbLower' : IDL.Float64,
  'timeframe' : Timeframe,
  'decisionEvent' : IDL.Text,
  'high' : IDL.Float64,
  'mode' : IDL.Text,
  'close' : IDL.Float64,
  'name' : IDL.Text,
  'open' : IDL.Float64,
  'time' : IDL.Text,
  'bbUpper' : IDL.Float64,
  'bbBasis' : IDL.Float64,
  'alertId' : IDL.Text,
  'pushThrough' : IDL.Bool,
  'inSession' : IDL.Bool,
  'minutesIntoBar' : IDL.Float64,
  'bandWidth' : IDL.Float64,
  'touchDepthRatio' : IDL.Float64,
  'touchDepth' : IDL.Float64,
  'signalType' : SignalType,
});
export const Timestamp = IDL.Nat;
export const Dataset = IDL.Record({
  'id' : DatasetId,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'rows' : IDL.Vec(SignalRow),
  'uploadedAt' : Timestamp,
});
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Settings = IDL.Record({
  'rsiEmbedLow' : IDL.Float64,
  'bbStdDev' : IDL.Float64,
  'rsiPeriod' : IDL.Nat,
  'rsiEmbedHigh' : IDL.Float64,
  'rsiOversold' : IDL.Float64,
  'rsiOverbought' : IDL.Float64,
  'bbLength' : IDL.Nat,
  'minMinutesIntoBar' : IDL.Float64,
  'minBandWidthRatio' : IDL.Float64,
});

export const idlService = IDL.Service({
  '__datasets' : IDL.Func(
      [IDL.Opt(DatasetId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(DatasetId, Dataset))],
      ['query'],
    ),
  '__nextId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__settings' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getDataset' : IDL.Func([DatasetId], [IDL.Opt(Dataset)], ['query']),
  'getDatasetRows' : IDL.Func(
      [DatasetId],
      [IDL.Opt(IDL.Vec(SignalRow))],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'listDatasets' : IDL.Func([], [IDL.Vec(Dataset)], ['query']),
  'updateSettings' : IDL.Func([Settings], [], []),
  'uploadDataset' : IDL.Func([IDL.Text, ExternalBlob], [DatasetId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DatasetId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Asset = IDL.Text;
  const Timeframe = IDL.Text;
  const SignalType = IDL.Variant({
    'snapbackLong' : IDL.Null,
    'pushThroughShort' : IDL.Null,
    'pushThroughLong' : IDL.Null,
    'snapbackShort' : IDL.Null,
    'noTrade' : IDL.Null,
  });
  const SignalRow = IDL.Record({
    'low' : IDL.Float64,
    'rsi' : IDL.Float64,
    'longSnapback' : IDL.Bool,
    'shortSnapback' : IDL.Bool,
    'ticker' : IDL.Text,
    'asset' : Asset,
    'bbLower' : IDL.Float64,
    'timeframe' : Timeframe,
    'decisionEvent' : IDL.Text,
    'high' : IDL.Float64,
    'mode' : IDL.Text,
    'close' : IDL.Float64,
    'name' : IDL.Text,
    'open' : IDL.Float64,
    'time' : IDL.Text,
    'bbUpper' : IDL.Float64,
    'bbBasis' : IDL.Float64,
    'alertId' : IDL.Text,
    'pushThrough' : IDL.Bool,
    'inSession' : IDL.Bool,
    'minutesIntoBar' : IDL.Float64,
    'bandWidth' : IDL.Float64,
    'touchDepthRatio' : IDL.Float64,
    'touchDepth' : IDL.Float64,
    'signalType' : SignalType,
  });
  const Timestamp = IDL.Nat;
  const Dataset = IDL.Record({
    'id' : DatasetId,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'rows' : IDL.Vec(SignalRow),
    'uploadedAt' : Timestamp,
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Settings = IDL.Record({
    'rsiEmbedLow' : IDL.Float64,
    'bbStdDev' : IDL.Float64,
    'rsiPeriod' : IDL.Nat,
    'rsiEmbedHigh' : IDL.Float64,
    'rsiOversold' : IDL.Float64,
    'rsiOverbought' : IDL.Float64,
    'bbLength' : IDL.Nat,
    'minMinutesIntoBar' : IDL.Float64,
    'minBandWidthRatio' : IDL.Float64,
  });
  
  return IDL.Service({
    '__datasets' : IDL.Func(
        [IDL.Opt(DatasetId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(DatasetId, Dataset))],
        ['query'],
      ),
    '__nextId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__settings' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getDataset' : IDL.Func([DatasetId], [IDL.Opt(Dataset)], ['query']),
    'getDatasetRows' : IDL.Func(
        [DatasetId],
        [IDL.Opt(IDL.Vec(SignalRow))],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'listDatasets' : IDL.Func([], [IDL.Vec(Dataset)], ['query']),
    'updateSettings' : IDL.Func([Settings], [], []),
    'uploadDataset' : IDL.Func([IDL.Text, ExternalBlob], [DatasetId], []),
  });
};

export const init = ({ IDL }) => { return []; };