/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Settings {
    rsiEmbedLow: number;
    bbStdDev: number;
    rsiPeriod: bigint;
    rsiEmbedHigh: number;
    rsiOversold: number;
    rsiOverbought: number;
    bbLength: bigint;
    minMinutesIntoBar: number;
    minBandWidthRatio: number;
}
export type Timestamp = bigint;
export interface SignalRow {
    low: number;
    rsi: number;
    longSnapback: boolean;
    shortSnapback: boolean;
    ticker: string;
    asset: Asset;
    bbLower: number;
    timeframe: Timeframe;
    decisionEvent: string;
    high: number;
    mode: string;
    close: number;
    name: string;
    open: number;
    time: string;
    bbUpper: number;
    bbBasis: number;
    alertId: string;
    pushThrough: boolean;
    inSession: boolean;
    minutesIntoBar: number;
    bandWidth: number;
    touchDepthRatio: number;
    touchDepth: number;
    signalType: SignalType;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Dataset {
    id: DatasetId;
    file: ExternalBlob;
    name: string;
    rows: Array<SignalRow>;
    uploadedAt: Timestamp;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Timeframe = string;
export type DatasetId = bigint;
export type Asset = string;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum SignalType {
    snapbackLong = "snapbackLong",
    pushThroughShort = "pushThroughShort",
    pushThroughLong = "pushThroughLong",
    snapbackShort = "snapbackShort",
    noTrade = "noTrade"
}
export interface backendInterface {
    __datasets(ko: DatasetId | null, count: bigint | null): Promise<Array<[DatasetId, Dataset]>>;
    __nextId(): Promise<any>;
    __settings(): Promise<any>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    getDataset(id: DatasetId): Promise<Dataset | null>;
    getDatasetRows(id: DatasetId): Promise<Array<SignalRow> | null>;
    getSettings(): Promise<Settings>;
    listDatasets(): Promise<Array<Dataset>>;
    updateSettings(newSettings: Settings): Promise<void>;
    uploadDataset(name: string, file: ExternalBlob): Promise<DatasetId>;
}
import type { Asset as _Asset, Dataset as _Dataset, DatasetId as _DatasetId, ExternalBlob as _ExternalBlob, SignalRow as _SignalRow, SignalType as _SignalType, Timeframe as _Timeframe, Timestamp as _Timestamp, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __datasets(arg0: DatasetId | null, arg1: bigint | null): Promise<Array<[DatasetId, Dataset]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__datasets(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__datasets(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __nextId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextId();
            return result;
        }
    }
    async __settings(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__settings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__settings();
            return result;
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async getDataset(arg0: DatasetId): Promise<Dataset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataset(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataset(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDatasetRows(arg0: DatasetId): Promise<Array<SignalRow> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDatasetRows(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDatasetRows(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async listDatasets(): Promise<Array<Dataset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDatasets();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDatasets();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async uploadDataset(arg0: string, arg1: ExternalBlob): Promise<DatasetId> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDataset(arg0, await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDataset(arg0, await to_candid_ExternalBlob_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Dataset_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dataset): Promise<Dataset> {
    return await from_candid_record_n6(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SignalRow_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalRow): SignalRow {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SignalType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalType): SignalType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Dataset]): Promise<Dataset | null> {
    return value.length === 0 ? null : await from_candid_Dataset_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_SignalRow>]): Array<SignalRow> | null {
    return value.length === 0 ? null : from_candid_vec_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: number;
    rsi: number;
    longSnapback: boolean;
    shortSnapback: boolean;
    ticker: string;
    asset: _Asset;
    bbLower: number;
    timeframe: _Timeframe;
    decisionEvent: string;
    high: number;
    mode: string;
    close: number;
    name: string;
    open: number;
    time: string;
    bbUpper: number;
    bbBasis: number;
    alertId: string;
    pushThrough: boolean;
    inSession: boolean;
    minutesIntoBar: number;
    bandWidth: number;
    touchDepthRatio: number;
    touchDepth: number;
    signalType: _SignalType;
}): {
    low: number;
    rsi: number;
    longSnapback: boolean;
    shortSnapback: boolean;
    ticker: string;
    asset: Asset;
    bbLower: number;
    timeframe: Timeframe;
    decisionEvent: string;
    high: number;
    mode: string;
    close: number;
    name: string;
    open: number;
    time: string;
    bbUpper: number;
    bbBasis: number;
    alertId: string;
    pushThrough: boolean;
    inSession: boolean;
    minutesIntoBar: number;
    bandWidth: number;
    touchDepthRatio: number;
    touchDepth: number;
    signalType: SignalType;
} {
    return {
        low: value.low,
        rsi: value.rsi,
        longSnapback: value.longSnapback,
        shortSnapback: value.shortSnapback,
        ticker: value.ticker,
        asset: value.asset,
        bbLower: value.bbLower,
        timeframe: value.timeframe,
        decisionEvent: value.decisionEvent,
        high: value.high,
        mode: value.mode,
        close: value.close,
        name: value.name,
        open: value.open,
        time: value.time,
        bbUpper: value.bbUpper,
        bbBasis: value.bbBasis,
        alertId: value.alertId,
        pushThrough: value.pushThrough,
        inSession: value.inSession,
        minutesIntoBar: value.minutesIntoBar,
        bandWidth: value.bandWidth,
        touchDepthRatio: value.touchDepthRatio,
        touchDepth: value.touchDepth,
        signalType: from_candid_SignalType_n11(_uploadFile, _downloadFile, value.signalType)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DatasetId;
    file: _ExternalBlob;
    name: string;
    rows: Array<_SignalRow>;
    uploadedAt: _Timestamp;
}): Promise<{
    id: DatasetId;
    file: ExternalBlob;
    name: string;
    rows: Array<SignalRow>;
    uploadedAt: Timestamp;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n7(_uploadFile, _downloadFile, value.file),
        name: value.name,
        rows: from_candid_vec_n8(_uploadFile, _downloadFile, value.rows),
        uploadedAt: value.uploadedAt
    };
}
async function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DatasetId, _Dataset]): Promise<[DatasetId, Dataset]> {
    return [
        value[0],
        await from_candid_Dataset_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    snapbackLong: null;
} | {
    pushThroughShort: null;
} | {
    pushThroughLong: null;
} | {
    snapbackShort: null;
} | {
    noTrade: null;
}): SignalType {
    return "snapbackLong" in value ? SignalType.snapbackLong : "pushThroughShort" in value ? SignalType.pushThroughShort : "pushThroughLong" in value ? SignalType.pushThroughLong : "snapbackShort" in value ? SignalType.snapbackShort : "noTrade" in value ? SignalType.noTrade : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Dataset>): Promise<Array<Dataset>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Dataset_n5(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DatasetId, _Dataset]>): Promise<Array<[DatasetId, Dataset]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n4(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignalRow>): Array<SignalRow> {
    return value.map((x)=>from_candid_SignalRow_n9(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DatasetId | null): [] | [_DatasetId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
